name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [17.x]

    steps: 
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-varsion }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-varsion }}
      - name: install modules
        run:  npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: unit testing
        run: npm run test:unit

        


